# Generated by Django 4.2.13 on 2024-08-03 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_drprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 8, 3, 23, 41, 9, 16019, tzinfo=datetime.timezone.utc)),
        ),
    ]
